-- Путь поиска модулей (важно!)
vim.opt.runtimepath:prepend(vim.fn.stdpath("config") .. "/lua")

require("core") -- Подключаем настройки и keymaps
require("core.options")
require("core.keymaps")
require("core.plugins")  -- Только подключает и вызывает Plug()

-- Подключаем конфигурации плагинов
require("plugins.lsp")
require("plugins.go")
require("plugins.telescope")
require("plugins.markdown")
require("plugins.ui")
require("plugins.go.go")
require("lua.plugins.go.helm")
require("plugins.ui.ui")

require("plugins.terraform.terraform")
require("plugins.misc.misc")
require("plugins.completion.completion")
require("utils")
require("plugins.formatting.formating")
require("utils")
require("plugins.go.go")
require("plugins.luasnip.luasnip")
require("plugins.go.dap")
require("plugins.misc.terminal")
require("plugins.ui.scrollbar")
require("plugins.treesitter.treesitter")
require("plugins.formatting.conform")
require("plugins.ansible.ansible")
require("plugins.testing.testing")
require("plugins.misc.whichkey")
require("plugins.misc.vista")
require("plugins.db.db")

require("plugins.groovy.groovy")
require("plugins.kubernetes.kubernetes")
require("plugins.filetypes.jet_filetype")
require("plugins.python.python")
require("plugins.oil.oil")
require("plugins.snacks.snacks")
require("plugins.go.todo")
require("plugins.algorithm.algorithm")
require("plugins.codewindow.codewindow")
require("plugins.github_actions.github_actions")
require("plugins.go.goplements")
require("lua.plugins.go.lsp_signature")
require("lua.plugins.go.struct_and_interface")
require("plugins.go.gosigns")